
-- 2026 NFL Playoff Player Pool
-- 14 Playoff Teams: DEN, NE, JAX, PIT, HOU, BUF, LAC (AFC) | SEA, CHI, PHI, CAR, LAR, SF, GB (NFC)
-- Bye Teams: DEN (AFC 1), SEA (NFC 1)
-- Players ranked by projected fantasy value within each position
-- Generated: 2026-01-08

-- First, clear existing data (respect FKs from rosters/player_scores)
DELETE FROM rosters;
DELETE FROM player_scores;
DELETE FROM player_pool;

INSERT INTO player_pool (player_key, espn_id, full_name, team, position, is_active)
VALUES
  -- ==================== QUARTERBACKS (14 starters + backups) ====================
  -- Starters (alphabetical)
  ('J.Allen-BUF-QB', '3918298', 'Josh Allen', 'BUF', 'QB', true),
  ('S.Darnold-SEA-QB', '3912547', 'Sam Darnold', 'SEA', 'QB', true),
  ('J.Herbert-LAC-QB', '4038941', 'Justin Herbert', 'LAC', 'QB', true),
  ('J.Hurts-PHI-QB', '4040715', 'Jalen Hurts', 'PHI', 'QB', true),
  ('T.Lawrence-JAX-QB', '4360310', 'Trevor Lawrence', 'JAX', 'QB', true),
  ('J.Love-GB-QB', '4036378', 'Jordan Love', 'GB', 'QB', true),
  ('D.Maye-NE-QB', '4431452', 'Drake Maye', 'NE', 'QB', true),
  ('B.Nix-DEN-QB', '4426338', 'Bo Nix', 'DEN', 'QB', true),
  ('B.Purdy-SF-QB', '4361741', 'Brock Purdy', 'SF', 'QB', true),
  ('A.Rodgers-PIT-QB', '8439', 'Aaron Rodgers', 'PIT', 'QB', true),
  ('M.Stafford-LAR-QB', '12483', 'Matthew Stafford', 'LAR', 'QB', true),
  ('C.Stroud-HOU-QB', '4432577', 'C.J. Stroud', 'HOU', 'QB', true),
  ('C.Williams-CHI-QB', '4431611', 'Caleb Williams', 'CHI', 'QB', true),
  ('B.Young-CAR-QB', '4685720', 'Bryce Young', 'CAR', 'QB', true),

  -- Backups
  ('M.Trubisky-BUF-QB', '3039707', 'Mitchell Trubisky', 'BUF', 'QB', true),
  ('S.Howell-PHI-QB', '4426875', 'Sam Howell', 'PHI', 'QB', true),
  ('T.Lance-LAC-QB', '4383351', 'Trey Lance', 'LAC', 'QB', true),
  ('J.Garoppolo-LAR-QB', '16760', 'Jimmy Garoppolo', 'LAR', 'QB', true),
  ('M.Jones-SF-QB', '4241464', 'Mac Jones', 'SF', 'QB', true),
  ('D.Ridder-GB-QB', '4239086', 'Desmond Ridder', 'GB', 'QB', true),
  ('T.Bagent-CHI-QB', '4434153', 'Tyson Bagent', 'CHI', 'QB', true),
  ('D.Mills-HOU-QB', '4242546', 'Davis Mills', 'HOU', 'QB', true),
  ('N.Mullens-JAX-QB', '3059989', 'Nick Mullens', 'JAX', 'QB', true),
  ('T.DeVito-NE-QB', '4240391', 'Tommy DeVito', 'NE', 'QB', true),
  ('S.Ehlinger-DEN-QB', '4241820', 'Sam Ehlinger', 'DEN', 'QB', true),
  ('D.Lock-SEA-QB', '3924327', 'Drew Lock', 'SEA', 'QB', true),
  ('W.Howard-PIT-QB', '4429955', 'Will Howard', 'PIT', 'QB', true),
  ('A.Dalton-CAR-QB', '14012', 'Andy Dalton', 'CAR', 'QB', true),

  -- ==================== RUNNING BACKS ====================
  -- Tier 1: Elite RBs (Bell Cows)
  ('S.Barkley-PHI-RB', '3929630', 'Saquon Barkley', 'PHI', 'RB', true),
  ('C.McCaffrey-SF-RB', '3117251', 'Christian McCaffrey', 'SF', 'RB', true),
  ('J.Jacobs-GB-RB', '4047365', 'Josh Jacobs', 'GB', 'RB', true),
  ('K.Williams-LAR-RB', '4430737', 'Kyren Williams', 'LAR', 'RB', true),
  ('K.Walker-SEA-RB', '4567048', 'Kenneth Walker III', 'SEA', 'RB', true),
  ('J.Cook-BUF-RB', '4379399', 'James Cook', 'BUF', 'RB', true),

  -- Tier 2: Strong RB1s
  ('T.Etienne-JAX-RB', '4239996', 'Travis Etienne Jr.', 'JAX', 'RB', true),
  ('D.Swift-CHI-RB', '4259545', 'D''Andre Swift', 'CHI', 'RB', true),
  ('R.Stevenson-NE-RB', '4569173', 'Rhamondre Stevenson', 'NE', 'RB', true),
  ('R.Dowdle-CAR-RB', '4038815', 'Rico Dowdle', 'CAR', 'RB', true),
  ('C.Hubbard-CAR-RB', '4241416', 'Chuba Hubbard', 'CAR', 'RB', true),
  ('O.Hampton-LAC-RB', '4685382', 'Omarion Hampton', 'LAC', 'RB', true),
  ('R.Harvey-DEN-RB', '4568490', 'RJ Harvey', 'DEN', 'RB', true),
  ('N.Chubb-HOU-RB', '3128720', 'Nick Chubb', 'HOU', 'RB', true),

  -- Tier 3: Solid RB2s / Flex plays
  ('J.Warren-PIT-RB', '4569987', 'Jaylen Warren', 'PIT', 'RB', true),
  ('K.Gainwell-PIT-RB', '4371733', 'Kenneth Gainwell', 'PIT', 'RB', true),
  ('T.Henderson-NE-RB', '4432710', 'TreVeyon Henderson', 'NE', 'RB', true),
  ('B.Corum-LAR-RB', '4429096', 'Blake Corum', 'LAR', 'RB', true),
  ('Z.Charbonnet-SEA-RB', '4426385', 'Zach Charbonnet', 'SEA', 'RB', true),
  ('I.Guerendo-SF-RB', '4372561', 'Isaac Guerendo', 'SF', 'RB', true),
  ('W.Marks-HOU-RB', '4429059', 'Woody Marks', 'HOU', 'RB', true),
  ('R.Davis-BUF-RB', '4429501', 'Ray Davis', 'BUF', 'RB', true),
  ('T.Bigsby-PHI-RB', '4429013', 'Tank Bigsby', 'PHI', 'RB', true),
  ('T.Etienne-CAR-RB', '4685350', 'Trevor Etienne', 'CAR', 'RB', true),
  ('L.Allen-JAX-RB', '4911851', 'LeQuint Allen Jr.', 'JAX', 'RB', true),
  ('E.Wilson-GB-RB', '4887558', 'Emanuel Wilson', 'GB', 'RB', true),
  ('J.McLaughlin-DEN-RB', '4722893', 'Jaleel McLaughlin', 'DEN', 'RB', true),
  ('K.Vidal-LAC-RB', '4430968', 'Kimani Vidal', 'LAC', 'RB', true),
  ('B.Robinson-SF-RB', '4241474', 'Brian Robinson Jr.', 'SF', 'RB', true),

  -- Tier 4: Depth RBs
  ('W.Shipley-PHI-RB', '4431545', 'Will Shipley', 'PHI', 'RB', true),
  ('A.Dillon-PHI-RB', '4239934', 'AJ Dillon', 'PHI', 'RB', true),
  ('K.Monangai-CHI-RB', '4608686', 'Kyle Monangai', 'CHI', 'RB', true),
  ('T.Badie-DEN-RB', '4362748', 'Tyler Badie', 'DEN', 'RB', true),
  ('H.Haskins-LAC-RB', '4372071', 'Hassan Haskins', 'LAC', 'RB', true),
  ('J.Patterson-LAC-RB', '4362452', 'Jaret Patterson', 'LAC', 'RB', true),
  ('C.Brooks-GB-RB', '3149687', 'Chris Brooks', 'GB', 'RB', true),
  ('T.Homer-CHI-RB', '4037457', 'Travis Homer', 'CHI', 'RB', true),
  ('D.Dallas-JAX-RB', '4240631', 'DeeJay Dallas', 'JAX', 'RB', true),
  ('B.Tuten-JAX-RB', '4882093', 'Bhayshul Tuten', 'JAX', 'RB', true),
  ('K.Johnson-PIT-RB', '4819231', 'Kaleb Johnson', 'PIT', 'RB', true),
  ('R.Rivers-LAR-RB', '4243003', 'Ronnie Rivers', 'LAR', 'RB', true),
  ('J.Hunter-LAR-RB', '4710341', 'Jarquez Hunter', 'LAR', 'RB', true),
  ('J.James-SF-RB', '4685397', 'Jordan James', 'SF', 'RB', true),
  ('D.Johnson-NE-RB', '3139602', 'D''Ernest Johnson', 'NE', 'RB', true),
  ('T.Johnson-BUF-RB', '3915411', 'Ty Johnson', 'BUF', 'RB', true),
  ('B.Brooks-HOU-RB', '4373273', 'British Brooks', 'HOU', 'RB', true),
  ('J.Jordan-HOU-RB', '4429939', 'Jawhar Jordan', 'HOU', 'RB', true),
  ('D.Ogunbowale-HOU-RB', '2983509', 'Dare Ogunbowale', 'HOU', 'RB', true),

  -- ==================== WIDE RECEIVERS ====================
  -- Tier 1: Elite WR1s
  ('A.Brown-PHI-WR', '4047646', 'A.J. Brown', 'PHI', 'WR', true),
  ('D.Smith-PHI-WR', '4241478', 'DeVonta Smith', 'PHI', 'WR', true),
  ('P.Nacua-LAR-WR', '4426515', 'Puka Nacua', 'LAR', 'WR', true),
  ('D.Adams-LAR-WR', '16800', 'Davante Adams', 'LAR', 'WR', true),
  ('J.Smith-Njigba-SEA-WR', '4430878', 'Jaxon Smith-Njigba', 'SEA', 'WR', true),
  ('S.Diggs-NE-WR', '2976212', 'Stefon Diggs', 'NE', 'WR', true),
  ('N.Collins-HOU-WR', '4258173', 'Nico Collins', 'HOU', 'WR', true),
  ('D.Moore-CHI-WR', '3915416', 'DJ Moore', 'CHI', 'WR', true),
  ('B.Thomas-JAX-WR', '4432773', 'Brian Thomas Jr.', 'JAX', 'WR', true),
  ('C.Sutton-DEN-WR', '3128429', 'Courtland Sutton', 'DEN', 'WR', true),

  -- Tier 2: Strong WR2s
  ('J.Reed-GB-WR', '4362249', 'Jayden Reed', 'GB', 'WR', true),
  ('C.Watson-GB-WR', '4248528', 'Christian Watson', 'GB', 'WR', true),
  ('R.Doubs-GB-WR', '4361432', 'Romeo Doubs', 'GB', 'WR', true),
  ('T.McMillan-CAR-WR', '4685472', 'Tetairoa McMillan', 'CAR', 'WR', true),
  ('X.Legette-CAR-WR', '4430034', 'Xavier Legette', 'CAR', 'WR', true),
  ('R.Odunze-CHI-WR', '4431299', 'Rome Odunze', 'CHI', 'WR', true),
  ('L.Burden-CHI-WR', '4685278', 'Luther Burden III', 'CHI', 'WR', true),
  ('L.McConkey-LAC-WR', '4612826', 'Ladd McConkey', 'LAC', 'WR', true),
  ('K.Allen-LAC-WR', '15818', 'Keenan Allen', 'LAC', 'WR', true),
  ('Q.Johnston-LAC-WR', '4429025', 'Quentin Johnston', 'LAC', 'WR', true),
  ('K.Shakir-BUF-WR', '4373678', 'Khalil Shakir', 'BUF', 'WR', true),
  ('K.Coleman-BUF-WR', '4635008', 'Keon Coleman', 'BUF', 'WR', true),
  ('C.Kirk-HOU-WR', '3895856', 'Christian Kirk', 'HOU', 'WR', true),
  ('C.Kupp-SEA-WR', '2977187', 'Cooper Kupp', 'SEA', 'WR', true),
  ('J.Jennings-SF-WR', '3886598', 'Jauan Jennings', 'SF', 'WR', true),
  ('M.Mims-DEN-WR', '4686472', 'Marvin Mims Jr.', 'DEN', 'WR', true),

  -- Tier 3: WR3s / Flex plays
  ('D.Metcalf-PIT-WR', '4047650', 'DK Metcalf', 'PIT', 'WR', true),
  ('A.Thielen-PIT-WR', '16460', 'Adam Thielen', 'PIT', 'WR', true),
  ('R.Pearsall-SF-WR', '4428209', 'Ricky Pearsall', 'SF', 'WR', true),
  ('T.Atwell-LAR-WR', '4360797', 'Tutu Atwell', 'LAR', 'WR', true),
  ('R.Shaheed-SEA-WR', '4032473', 'Rashid Shaheed', 'SEA', 'WR', true),
  ('J.Meyers-JAX-WR', '3916433', 'Jakobi Meyers', 'JAX', 'WR', true),
  ('T.Hunter-JAX-WR', '4685415', 'Travis Hunter', 'JAX', 'WR', true),
  ('P.Washington-JAX-WR', '4432620', 'Parker Washington', 'JAX', 'WR', true),
  ('T.Franklin-DEN-WR', '4431280', 'Troy Franklin', 'DEN', 'WR', true),
  ('D.Douglas-NE-WR', '4427095', 'DeMario Douglas', 'NE', 'WR', true),
  ('K.Boutte-NE-WR', '4429022', 'Kayshon Boutte', 'NE', 'WR', true),
  ('D.Wicks-GB-WR', '4428850', 'Dontayvion Wicks', 'GB', 'WR', true),
  ('J.Dotson-PHI-WR', '4361409', 'Jahan Dotson', 'PHI', 'WR', true),
  ('T.Harris-LAC-WR', '4686612', 'Tre'' Harris', 'LAC', 'WR', true),
  ('J.Coker-CAR-WR', '4695883', 'Jalen Coker', 'CAR', 'WR', true),
  ('R.Wilson-PIT-WR', '4431492', 'Roman Wilson', 'PIT', 'WR', true),

  -- Tier 4: Depth WRs
  ('B.Cooks-BUF-WR', '16731', 'Brandin Cooks', 'BUF', 'WR', true),
  ('G.Davis-BUF-WR', '4243537', 'Gabe Davis', 'BUF', 'WR', true),
  ('J.Palmer-BUF-WR', '4242433', 'Joshua Palmer', 'BUF', 'WR', true),
  ('T.Shavers-BUF-WR', '4241476', 'Tyrell Shavers', 'BUF', 'WR', true),
  ('D.Duvernay-CHI-WR', '4039050', 'Devin Duvernay', 'CHI', 'WR', true),
  ('O.Zaccheaus-CHI-WR', '3917914', 'Olamide Zaccheaus', 'CHI', 'WR', true),
  ('P.Bryant-DEN-WR', '4600981', 'Pat Bryant', 'DEN', 'WR', true),
  ('L.Humphrey-DEN-WR', '4039057', 'Lil''Jordan Humphrey', 'DEN', 'WR', true),
  ('B.Berrios-HOU-WR', '3123075', 'Braxton Berrios', 'HOU', 'WR', true),
  ('X.Hutchinson-HOU-WR', '4686422', 'Xavier Hutchinson', 'HOU', 'WR', true),
  ('J.Higgins-HOU-WR', '4877706', 'Jayden Higgins', 'HOU', 'WR', true),
  ('J.Noel-HOU-WR', '4586312', 'Jaylin Noel', 'HOU', 'WR', true),
  ('J.Watson-HOU-WR', '3118892', 'Justin Watson', 'HOU', 'WR', true),
  ('D.Brown-JAX-WR', '4361577', 'Dyami Brown', 'JAX', 'WR', true),
  ('T.Patrick-JAX-WR', '3134353', 'Tim Patrick', 'JAX', 'WR', true),
  ('D.Davis-LAC-WR', '4362477', 'Derius Davis', 'LAC', 'WR', true),
  ('K.Lambert-Smith-LAC-WR', '4430870', 'KeAndre Lambert-Smith', 'LAC', 'WR', true),
  ('K.Mumpfield-LAR-WR', '4710855', 'Konata Mumpfield', 'LAR', 'WR', true),
  ('B.Presley-LAR-WR', '4431342', 'Brennan Presley', 'LAR', 'WR', true),
  ('J.Whittington-LAR-WR', '4569382', 'Jordan Whittington', 'LAR', 'WR', true),
  ('X.Smith-LAR-WR', '4386544', 'Xavier Smith', 'LAR', 'WR', true),
  ('B.Covey-PHI-WR', '3926231', 'Britain Covey', 'PHI', 'WR', true),
  ('C.Austin-PIT-WR', '4243389', 'Calvin Austin III', 'PIT', 'WR', true),
  ('S.Miller-PIT-WR', '3914397', 'Scotty Miller', 'PIT', 'WR', true),
  ('B.Skowronek-PIT-WR', '4035656', 'Ben Skowronek', 'PIT', 'WR', true),
  ('M.Valdes-Scantling-PIT-WR', '3051738', 'Marquez Valdes-Scantling', 'PIT', 'WR', true),
  ('J.Bobo-SEA-WR', '4360405', 'Jake Bobo', 'SEA', 'WR', true),
  ('D.Young-SEA-WR', '4401805', 'Dareke Young', 'SEA', 'WR', true),
  ('K.Bourne-SF-WR', '3045523', 'Kendrick Bourne', 'SF', 'WR', true),
  ('S.Moore-SF-WR', '4430191', 'Skyy Moore', 'SF', 'WR', true),
  ('D.Robinson-SF-WR', '3043116', 'DeMarcus Robinson', 'SF', 'WR', true),
  ('J.Watkins-SF-WR', '4431466', 'Jordan Watkins', 'SF', 'WR', true),
  ('M.Golden-GB-WR', '4701936', 'Matthew Golden', 'GB', 'WR', true),
  ('J.Horn-CAR-WR', '4708486', 'Jimmy Horn Jr.', 'CAR', 'WR', true),
  ('K.Williams-NE-WR', '4613202', 'Kyle Williams', 'NE', 'WR', true),

  -- ==================== TIGHT ENDS ====================
  -- Tier 1: Elite TEs
  ('G.Kittle-SF-TE', '3040151', 'George Kittle', 'SF', 'TE', true),
  ('D.Goedert-PHI-TE', '3121023', 'Dallas Goedert', 'PHI', 'TE', true),
  ('E.Engram-DEN-TE', '3051876', 'Evan Engram', 'DEN', 'TE', true),

  -- Tier 2: Strong TE1s
  ('D.Schultz-HOU-TE', '3117256', 'Dalton Schultz', 'HOU', 'TE', true),
  ('T.Higbee-LAR-TE', '2573401', 'Tyler Higbee', 'LAR', 'TE', true),
  ('C.Kmet-CHI-TE', '4258595', 'Cole Kmet', 'CHI', 'TE', true),
  ('D.Kincaid-BUF-TE', '4385690', 'Dalton Kincaid', 'BUF', 'TE', true),
  ('P.Freiermuth-PIT-TE', '4361411', 'Pat Freiermuth', 'PIT', 'TE', true),
  ('H.Henry-NE-TE', '3046439', 'Hunter Henry', 'NE', 'TE', true),
  ('T.Kraft-GB-TE', '4572680', 'Tucker Kraft', 'GB', 'TE', true),

  -- Tier 3: Solid TEs
  ('B.Strange-JAX-TE', '4430539', 'Brenton Strange', 'JAX', 'TE', true),
  ('T.Conklin-LAC-TE', '3915486', 'Tyler Conklin', 'LAC', 'TE', true),
  ('W.Dissly-LAC-TE', '3127292', 'Will Dissly', 'LAC', 'TE', true),
  ('C.Loveland-CHI-TE', '4723086', 'Colston Loveland', 'CHI', 'TE', true),
  ('L.Musgrave-GB-TE', '4428085', 'Luke Musgrave', 'GB', 'TE', true),
  ('D.Knox-BUF-TE', '3930086', 'Dawson Knox', 'BUF', 'TE', true),
  ('T.Tremble-CAR-TE', '4372780', 'Tommy Tremble', 'CAR', 'TE', true),
  ('C.Stover-HOU-TE', '4426496', 'Cade Stover', 'HOU', 'TE', true),
  ('J.Smith-PIT-TE', '3054212', 'Jonnu Smith', 'PIT', 'TE', true),
  ('A.Barner-SEA-TE', '4576297', 'AJ Barner', 'SEA', 'TE', true),

  -- Tier 4: Depth TEs
  ('G.Calcaterra-PHI-TE', '4241374', 'Grant Calcaterra', 'PHI', 'TE', true),
  ('K.Granson-PHI-TE', '4039160', 'Kylen Granson', 'PHI', 'TE', true),
  ('C.Latu-PHI-TE', '4372026', 'Cameron Latu', 'PHI', 'TE', true),
  ('D.Allen-LAR-TE', '4426553', 'Davis Allen', 'LAR', 'TE', true),
  ('C.Parkinson-LAR-TE', '4242557', 'Colby Parkinson', 'LAR', 'TE', true),
  ('N.Vannett-LAR-TE', '2576399', 'Nick Vannett', 'LAR', 'TE', true),
  ('T.Ferguson-LAR-TE', '4570037', 'Terrance Ferguson', 'LAR', 'TE', true),
  ('D.Smythe-CHI-TE', '3052897', 'Durham Smythe', 'CHI', 'TE', true),
  ('N.Adkins-DEN-TE', '4383440', 'Nate Adkins', 'DEN', 'TE', true),
  ('A.Trautman-DEN-TE', '3911853', 'Adam Trautman', 'DEN', 'TE', true),
  ('H.Bryant-HOU-TE', '4040774', 'Harrison Bryant', 'HOU', 'TE', true),
  ('H.Long-JAX-TE', '4239944', 'Hunter Long', 'JAX', 'TE', true),
  ('Q.Morris-JAX-TE', '4244049', 'Quintin Morris', 'JAX', 'TE', true),
  ('J.Mundt-JAX-TE', '3052096', 'Johnny Mundt', 'JAX', 'TE', true),
  ('J.Akins-JAX-TE', '3128452', 'Jordan Akins', 'JAX', 'TE', true),
  ('O.Gadsden-LAC-TE', '4595342', 'Oronde Gadsden', 'LAC', 'TE', true),
  ('A.Hooper-NE-TE', '3043275', 'Austin Hooper', 'NE', 'TE', true),
  ('C.Dippre-NE-TE', '4596545', 'CJ Dippre', 'NE', 'TE', true),
  ('J.Westover-NE-TE', '4361100', 'Jack Westover', 'NE', 'TE', true),
  ('C.Heyward-PIT-TE', '4241961', 'Connor Heyward', 'PIT', 'TE', true),
  ('J.Whyle-GB-TE', '4360086', 'Josh Whyle', 'GB', 'TE', true),
  ('M.Evans-CAR-TE', '4683243', 'Mitchell Evans', 'CAR', 'TE', true),
  ('J.Mitchell-CAR-TE', '4361988', 'James Mitchell', 'CAR', 'TE', true),
  ('J.Hawes-BUF-TE', '4573699', 'Jackson Hawes', 'BUF', 'TE', true),
  ('K.Latu-BUF-TE', '4688552', 'Keleki Latu', 'BUF', 'TE', true),
  ('L.Farrell-SF-TE', '4040612', 'Luke Farrell', 'SF', 'TE', true),
  ('J.Tonges-SF-TE', '4259147', 'Jake Tonges', 'SF', 'TE', true),
  ('N.Kallerup-SEA-TE', '4569547', 'Nick Kallerup', 'SEA', 'TE', true),
  ('E.Saubert-SEA-TE', '2975863', 'Eric Saubert', 'SEA', 'TE', true),
  ('L.Krull-DEN-TE', '4360231', 'Lucas Krull', 'DEN', 'TE', true),
  ('M.Lewis-DEN-TE', '9614', 'Marcedes Lewis', 'DEN', 'TE', true),
  ('C.Lohner-DEN-TE', '4432208', 'Caleb Lohner', 'DEN', 'TE', true),
  ('P.Murtagh-DEN-TE', '5209791', 'Patrick Murtagh', 'DEN', 'TE', true),
  ('M.Lang-NE-TE', '4566195', 'Marshall Lang', 'NE', 'TE', true),
  ('T.Odukoya-NE-TE', '4363554', 'Thomas Odukoya', 'NE', 'TE', true),
  ('P.Herbert-JAX-TE', '4429811', 'Patrick Herbert', 'JAX', 'TE', true),
  ('D.Parham-PIT-TE', '3912092', 'Donald Parham Jr.', 'PIT', 'TE', true),
  ('D.Washington-PIT-TE', '4430802', 'Darnell Washington', 'PIT', 'TE', true),
  ('J.Bell-PIT-TE', '4429262', 'Jaheim Bell', 'PIT', 'TE', true),
  ('M.Sokol-PIT-TE', '3121378', 'Matt Sokol', 'PIT', 'TE', true),
  ('B.Jordan-HOU-TE', '4362504', 'Brevin Jordan', 'HOU', 'TE', true),
  ('L.Lachey-HOU-TE', '4432338', 'Luke Lachey', 'HOU', 'TE', true),
  ('L.Pryor-HOU-TE', '4878842', 'Layne Pryor', 'HOU', 'TE', true),
  ('T.Fisk-LAC-TE', '4242558', 'Tucker Fisk', 'LAC', 'TE', true),
  ('T.Yassmin-LAC-TE', '4361027', 'Thomas Yassmin', 'LAC', 'TE', true),
  ('E.Arroyo-SEA-TE', '4678006', 'Elijah Arroyo', 'SEA', 'TE', true),
  ('S.Carlson-CHI-TE', '3948283', 'Stephen Carlson', 'CHI', 'TE', true),
  ('T.Gordon-CHI-TE', '4569615', 'Thomas Gordon', 'CHI', 'TE', true),
  ('Q.Ismail-CHI-TE', '4379769', 'Qadir Ismail', 'CHI', 'TE', true),
  ('N.Kalinic-CHI-TE', '4916349', 'Nikola Kalinic', 'CHI', 'TE', true),
  ('E.Jenkins-PHI-TE', '4248557', 'E.J. Jenkins', 'PHI', 'TE', true),
  ('J.Sanders-CAR-TE', '4431588', 'Ja''Tavion Sanders', 'CAR', 'TE', true),
  ('R.Dwelley-CAR-TE', '3120303', 'Ross Dwelley', 'CAR', 'TE', true),
  ('B.Pierre-CAR-TE', '5082648', 'Bryce Pierre', 'CAR', 'TE', true),
  ('B.Willis-SF-TE', '4360290', 'Brayden Willis', 'SF', 'TE', true),
  ('J.FitzPatrick-GB-TE', '4379401', 'John FitzPatrick', 'GB', 'TE', true),
  ('M.Castles-GB-TE', '4372741', 'McCallan Castles', 'GB', 'TE', true),
  ('D.Dabney-GB-TE', '4429466', 'Drake Dabney', 'GB', 'TE', true),
  ('M.Swinson-GB-TE', '4362770', 'Messiah Swinson', 'GB', 'TE', true),

  -- ==================== KICKERS ====================
  ('M.Prater-BUF-K', '11122', 'Matt Prater', 'BUF', 'K', true),
  ('J.Elliott-PHI-K', '3050478', 'Jake Elliott', 'PHI', 'K', true),
  ('C.Boswell-PIT-K', '17372', 'Chris Boswell', 'PIT', 'K', true),
  ('C.Dicker-LAC-K', '4362081', 'Cameron Dicker', 'LAC', 'K', true),
  ('J.Myers-SEA-K', '2473037', 'Jason Myers', 'SEA', 'K', true),
  ('E.Pineiro-SF-K', '4034949', 'Eddy Pineiro', 'SF', 'K', true),
  ('B.McManus-GB-K', '16339', 'Brandon McManus', 'GB', 'K', true),
  ('C.Santos-CHI-K', '17427', 'Cairo Santos', 'CHI', 'K', true),
  ('K.Fairbairn-HOU-K', '2971573', 'Ka''imi Fairbairn', 'HOU', 'K', true),
  ('C.Cam-JAX-K', '4686361', 'Cam Little', 'JAX', 'K', true),
  ('J.Lutz-DEN-K', '2985659', 'Wil Lutz', 'DEN', 'K', true),
  ('A.Borregales-NE-K', '4569923', 'Andy Borregales', 'NE', 'K', true),
  ('H.Mevis-LAR-K', '4574716', 'Harrison Mevis', 'LAR', 'K', true),
  ('R.Fitzgerald-CAR-K', '4568263', 'Ryan Fitzgerald', 'CAR', 'K', true),

  -- ==================== DEFENSES ====================
  ('BUF-DEF', 'BUF', 'Buffalo Bills', 'BUF', 'DST', true),
  ('PHI-DEF', 'PHI', 'Philadelphia Eagles', 'PHI', 'DST', true),
  ('DEN-DEF', 'DEN', 'Denver Broncos', 'DEN', 'DST', true),
  ('LAC-DEF', 'LAC', 'Los Angeles Chargers', 'LAC', 'DST', true),
  ('PIT-DEF', 'PIT', 'Pittsburgh Steelers', 'PIT', 'DST', true),
  ('SF-DEF', 'SF', 'San Francisco 49ers', 'SF', 'DST', true),
  ('HOU-DEF', 'HOU', 'Houston Texans', 'HOU', 'DST', true),
  ('GB-DEF', 'GB', 'Green Bay Packers', 'GB', 'DST', true),
  ('SEA-DEF', 'SEA', 'Seattle Seahawks', 'SEA', 'DST', true),
  ('CHI-DEF', 'CHI', 'Chicago Bears', 'CHI', 'DST', true),
  ('LAR-DEF', 'LAR', 'Los Angeles Rams', 'LAR', 'DST', true),
  ('NE-DEF', 'NE', 'New England Patriots', 'NE', 'DST', true),
  ('JAX-DEF', 'JAX', 'Jacksonville Jaguars', 'JAX', 'DST', true),
  ('CAR-DEF', 'CAR', 'Carolina Panthers', 'CAR', 'DST', true)

ON CONFLICT (player_key) DO UPDATE SET
  espn_id = EXCLUDED.espn_id,
  full_name = EXCLUDED.full_name,
  team = EXCLUDED.team,
  position = EXCLUDED.position,
  is_active = EXCLUDED.is_active;
